[package]
name = "weather-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
reqwest = "0.11.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.80"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
lazy_static = "1.4.0"